spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: service-auth
  redis:
    host: 192.168.100.203

server:
  port: 8781

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

logging.level.org.springframework.security: DEBUG
logging.leve.org.springframework: DEBUG

#http://localhost:8781/oauth/token?grant_type=password&username=user_2&password=123456&client_id=client_2&client_secret=123456
