eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8764

spring:
  profiles:
    active: dev,data
  application:
    name: system-data
  zipkin:
    base-url: http://localhost:9411
