spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user
    username: root
    password: r123456
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  redis:
    database: 8
    host: 192.168.100.223
    port: 6379
    password:


mybatis:
  typeAliasesPackage: com.likesea.system.domain
  mapperLocations: classpath*:mappers.user/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
